version: '3.8'

services:
    api:
        build: ./aurora/backend/
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
        volumes:
            - ./aurora/backend/:/usr/src/aurora
        ports:
            - 8000:8000
        image: aurora_api:latest
    app:
        build: ./aurora/frontend
        command: streamlit run app/main.py --server.port 8501
        volumes:
            - ./aurora/frontend/:/usr/src/streamlit
        ports:
            - 8501:8501
        image: aurora_app:latest
