name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Pytest
      run: pip install -r aurora/backend/requirements.txt
    - name: debug
      run: pwd
    - name: run pytest
      run: python -m pytest aurora/backend
    - name: Upload coverage
      uses: codecov/codecov-action@v1

