name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Change directory
      run: cd aurora/backend
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run pytest
      run: pytest
    - name: Upload coverage
      uses: codecov/codecov-action@v1
